/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewsIndexRouteImport } from './routes/reviews/index'
import { Route as ReviewsNewRouteImport } from './routes/reviews/new'
import { Route as ReviewsReviewIdRouteImport } from './routes/reviews/$reviewId'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIndexRoute = ReviewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsRoute,
} as any)
const ReviewsNewRoute = ReviewsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReviewsRoute,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: '/$reviewId',
  path: '/$reviewId',
  getParentRoute: () => ReviewsRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/$': typeof ApiSplatRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/reviews': typeof ReviewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reviews': typeof ReviewsRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/reviews/$reviewId': typeof ReviewsReviewIdRoute
  '/reviews/new': typeof ReviewsNewRoute
  '/reviews/': typeof ReviewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reviews'
    | '/api/$'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/reviews/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/$' | '/reviews/$reviewId' | '/reviews/new' | '/reviews'
  id:
    | '__root__'
    | '/'
    | '/reviews'
    | '/api/$'
    | '/reviews/$reviewId'
    | '/reviews/new'
    | '/reviews/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewsRoute: typeof ReviewsRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/': {
      id: '/reviews/'
      path: '/'
      fullPath: '/reviews/'
      preLoaderRoute: typeof ReviewsIndexRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/reviews/new': {
      id: '/reviews/new'
      path: '/new'
      fullPath: '/reviews/new'
      preLoaderRoute: typeof ReviewsNewRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/reviews/$reviewId': {
      id: '/reviews/$reviewId'
      path: '/$reviewId'
      fullPath: '/reviews/$reviewId'
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof ReviewsRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReviewsRouteChildren {
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
  ReviewsNewRoute: typeof ReviewsNewRoute
  ReviewsIndexRoute: typeof ReviewsIndexRoute
}

const ReviewsRouteChildren: ReviewsRouteChildren = {
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
  ReviewsNewRoute: ReviewsNewRoute,
  ReviewsIndexRoute: ReviewsIndexRoute,
}

const ReviewsRouteWithChildren =
  ReviewsRoute._addFileChildren(ReviewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewsRoute: ReviewsRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
